spring.application.name=smart-campus-api
server.port=8082

spring.data.mongodb.uri=mongodb+srv://user:jU5WNBcw3dO3G3BL@cluster0.v6wxgah.mongodb.net/smart_campus_db?appName=Cluster0&maxPoolSize=50&minPoolSize=10&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&socketTimeoutMS=30000

# MongoDB Connection Timeout Settings
spring.data.mongodb.socket-timeout=30000
spring.data.mongodb.connect-timeout=10000
spring.data.mongodb.max-wait-time=30000

jwt.secret=9a4f2c8d3e1f5b6a7c0e9d8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b
jwt.expiration-ms=1800000

# -- Google OAuth2 (Students only -- @my.sliit.lk) -------------
spring.security.oauth2.client.registration.google.client-id=220355778246-5glp47iosc5nj90kkf3qodhjfe40ts9p.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# Application Configuration
app.frontend-url=http://localhost:5173
app.check-in.scan-buffer-minutes=15
app.check-in.manual-buffer-minutes=10
